### ISSUE TITLE
TLS certificate ran out 2 days ago

### ISSUE THREAD

**Issue by toothbrush7777777** [pypa/pypa.io#10]
The certificate for https://pypa.io/ ran out on the 12<sup>th</sup> of December.

**Comment by ncoghlan** [comment]
Ping @dstufft @qwcode (I'm not sure who has access to update the cert on pypa.io)

**Comment by dstufft** [comment]
I poked @malemburg the other day about getting a new cert. I think the PSF StartSSL validation ran out and he was working on getting it renewed.

**Comment by malemburg** [comment]
Right. Getting the validation updated will take a few more days.

**Comment by dstufft** [comment]
(Just to be clear, I dropped the ball on this, I moved on Dec 11th and it totally got lost in the cracks)

**Comment by ncoghlan** [comment]
Ah, I'd seen MAL's note about renewing the validation, but hadn't connected the dots to the pypa.io cert.

**Comment by dstufft** [comment]
Thanks to @malemburg we have a fancy new 3 year certificate that I've just installed.
