### ISSUE TITLE
pypa.io 404s

### ISSUE THREAD

**Issue by ddbeck** [pypa/pypa.io#15]
www.pypa.io redirects to https://www.pypa.io/en/latest/, which is a 404 page. Perhaps relatedly, it appears the most recent pypa.io build on Read the Docs has failed. It seems to have been doing this for about 24 hours now.

This is a little bit of a problem for docs that [use the pypa.io intersphinx inventory](https://github.com/pypa/python-packaging-user-guide/pull/227).

**Comment by xavfernandez** [comment]
For the record it was:

    <dstufft> pypa.io got assigned to a different project by accident
    <dstufft> I have to wait for RTD to fix it

and it finally got fixed this morning:

    <ericholscher> dstufft: I deleted that domain

https://pypa.io works again and this can be closed :)

**Comment by ddbeck** [comment]
Thanks!
