### ISSUE TITLE
Link from How to Help is broken

### ISSUE THREAD

**Issue by michaelmhoffman** [pypa/pypa.io#18]
The link on https://www.pypa.io/en/latest/help/

> Get involved with one of mainstream :ref:`packaging projects <pypug:projects>`.

goes to a page not found, https://packaging.python.org/projects/#projects

**Comment by pradyunsg** [comment]
That page exists... I think this can be closed.

**Comment by michaelmhoffman** [comment]
That URL does not exist, but it looks like the link has changed.
