### ISSUE TITLE
SSL not work on https://pypa.io

### ISSUE THREAD

**Issue by b3nab** [pypa/pypa.io#21]
Sometimes when I go to https://pypa.io without insert www. at the beginning I got a Chrome error saying that the certificate is not valid and for this reason I'm not able to enter the site. Otherwise when I enter in https://www.pypa.io all seems to work fine.

My suggestion is to implement the redirect every time someone hit pypa.io and redirect the page to www.pypa.io

**Comment by circlehk** [comment]
The issue is still valid. https://pypa.io is using an revoked HTTPS certificate:
![image](https://user-images.githubusercontent.com/9265283/32792277-f141057c-c99d-11e7-9eb4-e9d59d95b873.png)

Probably the site was missed out from the last cert renewal exercise. Like @b3nab said, the www site is fine and using a valid certificate

**Comment by Poogles** [comment]
It's down to StartComs certs being revoked [here](https://arstechnica.com/information-technology/2017/07/google-drops-the-boom-on-wosign-startcom-certs-for-good/).  It looks like it affects the wildcard, so the documentation for pipfile for example is broken.

**Comment by brainwane** [comment]
I just ran into this --  https://pypa.io does not display in Chrome because of a revoked certificate from  Issuer: StartCom Class 3 OV Server CA. As the Warehouse project ramps up and I'm pointing more people to relevant PyPA pages on pypa.io I'd love for this to be addressed.

**Comment by deejoe** [comment]
Just hit this today also.

**Comment by brainwane** [comment]
On [the pypa-dev mailing list](https://groups.google.com/forum/#!msg/pypa-dev/jzXR3A3E-dw/EdrQgPYWAwAJ) @MarkMangoba said he'd be pinging the PSF infrastructure team about this -- Mark, any word?

**Comment by ewdurbin** [comment]
Resolved. We moved to LetsEncrypt! to avoid this in the future.

**Comment by b3nab** [comment]
@ewdurbin Good news, so I think that this issue can be closed. Thanks all! :)
