### ISSUE TITLE
Update distutils-sig description (including a CoC link)

### ISSUE THREAD

**Issue by ncoghlan** [pypa/pypa.io#33]
The current distutils-sig list description is thoroughly out of date these days, and we should also add a link to the PyPA CoC from the description: https://www.pypa.io/en/latest/code-of-conduct/

**Comment by ncoghlan** [comment]
Victor Stinner pointed out that the PyPA CoC wording assumes that there's a clearly identifiable list of project maintainers, which we generally have for the project repos (via https://github.com/orgs/pypa/teams?utf8=%E2%9C%93&query=+visibility%3Avisible ), but don't really have for distutils-sig itself.

Given that, the PSF CoC (which nominates the PSF Board and Director of Operations as potential contact channels) may be a better option: https://www.python.org/psf/codeofconduct/

**Comment by ncoghlan** [comment]
(Referencing both is also an option, since the PyPA CoC has more specifics on behavioural expectations than the PSF one does)

**Comment by cooperlees** [comment]
I added links to both to the PyPA-Committers Information section in mailman 3 (which in turn seems to come up as the "Summary" on the info page). 

Do we want one or the other in the "Description" field? I don't see any other mailman list do this (in mailman3)

**Comment by ncoghlan** [comment]
I'm pretty sure those fields were called Summary and Description in MM2 (rather than Description and Info), but it's also possible I just misremembered the names.

Anyway, I've updated the distutils-sig info page to reference the PSF CoC, as well as modernised the list description and the documentation links: https://mail.python.org/mm3/mailman3/lists/distutils-sig.python.org/
