### ISSUE TITLE
Remove CLA from Weblate

### ISSUE THREAD

**Issue by comradekingu** [pypa/pypa.io#51]
I can't fix failing checks, of which there are many, from the PyPa translation without agreeing to the CoC terms. I am making the effort to ask you to remove it. The contributions of others, and mine, are still in the string-base without it. The actual platform you are using removed the CoC employed.

**Comment by di** [comment]
@comradekingu Are you talking about https://www.pypa.io/en/latest/code-of-conduct/?

**Comment by di** [comment]
Ah, I see now that Weblate is interpreting the "Contributor Agreement" as a license agreement, when we really just wanted to specify a code of conduct. I've removed it.
