### ISSUE TITLE
Roadmap: Build Neutrality

### ISSUE THREAD

**Issue by guettli** [pypa/pypa.io#8]
From http://pypaio.readthedocs.org/en/roadmap/roadmap/

> Build Neutrality
> Summary: An attempt to specify a tool-neutral Build API, that pip will adopt, with the goal being to easily support other build systems besides setuptools/distutils.

I am missing something here:

What is meant with "other build systems besides setuptools/distutils"?

Are there existing build systems which already exist? Or does
this mean build systems which could be created in the future?

If the first (existing build system), then please add the most important there.

I am afraid that this kind of neutrality makes things much more complicated and much less "getting things done".

Background: I switched from Java to Python since the "Enterprise JavaBeans" was just a "bla bla" standard. I wanted working code which I found in the python world, not N implementations of a standard. One working implementation is enough :-)

**Comment by qwcode** [comment]
one existing example that comes up often is Bento (https://cournape.github.io/Bento/)

but I don't think it's about supporting a certain alternative at the moment, more just that we don't want to lock into a single tool for the build function...

as for simplicity for the "average" user, I think at any given time, there's likely to be a clear "winner" that the PyPUG will recommend...  and for now, that's still setuptools

**Comment by guettli** [comment]
One thing I learned from programming during the last years (I started with 14 and I am 39 now): Don't code for the future. You don't know the future, nobody does. Do clean coding today, not more.

I just can't get this, according to my opinion, useless "dance": let's do something that might be useful in the future. If the code is clean and tested, then it is easy to do refactoring. There is no need to fear to drive into a dead end. If you need a feature later, you can add it **later**. First get it done :-)

**Comment by ncoghlan** [comment]
There's no issue here, only an attempt to dictate to volunteers how they should spend their time.
