### ISSUE TITLE
logo is missing

### ISSUE THREAD

**Issue by kwhkim** [pypa/pypa.io#81]
logo image link is broken in https://www.pypa.io/en/latest/
just below the paragraph of "Click the logo below to download pip, the most prominent software used to interact with PyPI."

**Comment by di** [comment]
Transferred. I'm not really sure what this logo/link was supposed to be doing... a link to download pip? But it was changed from warehouse in https://github.com/pypa/pypa.io/commit/a7f030b4b9cd1f5748e3f1dc88032b6de00ee894? @ewdurbin any ideas why you did that?

**Comment by ewdurbin** [comment]
It was added to appease some trademark filing bureaucrat.

**Comment by pradyunsg** [comment]
Beyond that, this is broken because I think the static assets are served with a cache-busting hash included in the URL.

So, the current URL for logo-large.svg is https://pypi.org/static/images/logo-large.6bdbb439.svg
